apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-static
  labels:
    app: cafe-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-static
  template:
    metadata:
      labels:
        app: cafe-static
    spec:
      serviceAccountName: app-sa
      containers:
      - name: cafe-static
        image: image-registry.openshift-image-registry.svc:5000/ci/cafe-static:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
