apiVersion: v1
kind: Service
metadata:
  name: cafe-static
  labels:
    app: cafe-static
spec:
  selector:
    app: cafe-static
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
