apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-static-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-static
      version: green
  template:
    metadata:
      labels:
        app: cafe-static
        version: green
    spec:
      containers:
      - name: cafe-static
        image: image-registry.openshift-image-registry.svc:5000/ci/cafe-static:v2
        ports:
        - containerPort: 8080
